[configure]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/configure.sh
parameters:
type:script
message:Configuring OCN Fixed IP (IPoE) tunnel
description:Configure OCN Fixed IP (IPoE) (IPIP) tunnel

[start]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/configure.sh
parameters: start
type:script
message:Starting OCN Fixed IP (IPoE) tunnel

[stop]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/teardown.sh
parameters:
type:script
message:Stopping OCN Fixed IP (IPoE) tunnel

[restart]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/configure.sh
parameters: restart
type:script
message:Restarting OCN Fixed IP (IPoE) tunnel

[status]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/status.sh
parameters:
type:script_output
message:OCN Fixed IP (IPoE) tunnel status

[diagnostics]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/diagnostics.sh
parameters:
type:script_output
message:OCN Fixed IP (IPoE) diagnostics
