[configure]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/configure.sh
parameters:
type:script
message:Configuring OCN Virtual Connect Fixed IP tunnel
description:Configure OCN Virtual Connect Fixed IP (IPIP) tunnel

[start]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/configure.sh
parameters: start
type:script
message:Starting OCN Virtual Connect Fixed IP tunnel

[stop]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/teardown.sh
parameters:
type:script
message:Stopping OCN Virtual Connect Fixed IP tunnel

[restart]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/configure.sh
parameters: restart
type:script
message:Restarting OCN Virtual Connect Fixed IP tunnel

[status]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/status.sh
parameters:
type:script_output
message:OCN Virtual Connect Fixed IP tunnel status

[diagnostics]
command:/usr/local/opnsense/scripts/OPNsense/ocnfixedip/diagnostics.sh
parameters:
type:script_output
message:OCN Virtual Connect Fixed IP diagnostics
