[configure]
command:/usr/local/opnsense/scripts/OPNsense/dslite/configure.sh
parameters:
type:script
message:Configuring DS-Lite tunnel
description:Configure DS-Lite tunnel

[start]
command:/usr/local/opnsense/scripts/OPNsense/dslite/configure.sh
parameters: start
type:script
message:Starting DS-Lite tunnel

[stop]
command:/usr/local/opnsense/scripts/OPNsense/dslite/teardown.sh
parameters:
type:script
message:Stopping DS-Lite tunnel

[restart]
command:/usr/local/opnsense/scripts/OPNsense/dslite/configure.sh
parameters: restart
type:script
message:Restarting DS-Lite tunnel

[status]
command:/usr/local/opnsense/scripts/OPNsense/dslite/status.sh
parameters:
type:script_output
message:DS-Lite tunnel status

[diagnostics]
command:/usr/local/opnsense/scripts/OPNsense/dslite/diagnostics.sh
parameters:
type:script_output
message:DS-Lite diagnostics
